### ISSUE TITLE
Get annual energy balances from Eurostat

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#100]
Energy consumption by sector (industry subsectors, commercial, household, agriculture, and others) as well as by fuel type (solid and liquid fossils, gas, biofuels, renewables, waste, district heat, direct electricity, etc.) are available on Eurostat (nrg_bal_c), as well as the allocation of that consumption to end uses for households (space heat, water heat, cooking - nrg_d_hhq). This is the starting point for calculating annual energy demands for each country for the years 2000-2018.

On top of this, to include Switzerland in everything, specific [Swiss datasets](https://www.bfe.admin.ch/bfe/de/home/versorgung/statistik-und-geodaten/energiestatistiken.html) need to be processed alongside the Eurostat datasets.

Together, these are currently processed in our sector-coupled sibling [here](https://github.com/calliope-project/euro-calliope-2.0/blob/main/src/construct/annual_energy_balance.py), including grouping carriers to a subset of interest and combining Eurostat and Swiss energy balances and household end uses.

**Comment by brynpickering** [comment]
Eurostat data could be accessed much easier with a [pandas wrapper](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#remote-data-eurostat)

**Comment by timtroendle** [comment]
Definition of done: tidy dataframe (csv) or netcdf with indices country, year, subsector, energy carrier.

**Comment by brynpickering** [comment]
> Definition of done: tidy dataframe (csv) or netcdf� with indices country, year, subsector, energy carrier.

Header looks like this:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th>value</th>
    </tr>
    <tr>
      <th>cat_code</th>
      <th>carrier_code</th>
      <th>unit</th>
      <th>country</th>
      <th>year</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">AFC</th>
      <th rowspan="5" valign="top">BIOE</th>
      <th rowspan="5" valign="top">TJ</th>
      <th rowspan="5" valign="top">AL</th>
      <th>1990.0</th>
      <td>15199.0</td>
    </tr>
    <tr>
      <th>1991.0</th>
      <td>15199.0</td>
    </tr>
    <tr>
      <th>1992.0</th>
      <td>15199.0</td>
    </tr>
    <tr>
      <th>1993.0</th>
      <td>14507.0</td>
    </tr>
    <tr>
      <th>1994.0</th>
      <td>13847.0</td>
    </tr>
  </tbody>
</table>

**Comment by brynpickering** [comment]
Fixed in #113
