### ISSUE TITLE
Annual heat demand

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#101]
The annual energy balances from a mix of data sources is the starting point to understand annual demands in many sectors. For building heat, this requires converting energy consumption to demand, based on assumptions of technology efficiency (e.g. 90-99% for gas boilers). The three building types considered are: households, commercial sector, other (agriculture, fisheries, and 'non-specified other'). 

The tasks are:

1. Get energy consumption per end-use in households (already processed in #100, with an added cleanup of renewables)
2. Get energy consumption per end-use in the commercial sector (requires JRC-IDEES and a specific Swiss dataset)
3. Clean up some countries outside the scope of input datasets (e.g. Iceland gets all its heat from geothermal, which we ignore)
4. Go from consumption to demand, using configurable efficiencies
5. Fill empty data from certain years with average, normalised end-use consumption scaled by Eurostat total household energy consumption.

This is undertaken in our sector-coupled sibling [here](https://github.com/calliope-project/euro-calliope-2.0/blob/main/src/construct/annual_heat_demand.py)

**Comment by timtroendle** [comment]
Blocked by #100.

**Comment by timtroendle** [comment]
We are planning to add the pre-processed JRC-IDEES dataset in the `data` repository (the current folder or another location), as it is only available upon request but we are allowed to re-distribute.

**Comment by timtroendle** [comment]
Definition of done: tidy dataframe (csv) or netcdf with indices country, year, subsector, energy carrier.

**Comment by brynpickering** [comment]
> Definition of done: tidy dataframe (csv) or netcdf with indices country, year, subsector, energy carrier.

It will look like this:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th>value</th>
    </tr>
    <tr>
      <th>country_code</th>
      <th>year</th>
      <th>unit</th>
      <th>end_use</th>
      <th>cat_name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">ALB</th>
      <th rowspan="5" valign="top">2000</th>
      <th rowspan="5" valign="top">twh</th>
      <th rowspan="2" valign="top">cooking</th>
      <th>commercial</th>
      <td>0.079437</td>
    </tr>
    <tr>
      <th>household</th>
      <td>0.382355</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">space_heat</th>
      <th>commercial</th>
      <td>1.135662</td>
    </tr>
    <tr>
      <th>household</th>
      <td>1.258562</td>
    </tr>
    <tr>
      <th>water_heat</th>
      <th>commercial</th>
      <td>0.113575</td>
    </tr>
  </tbody>
</table>

**Comment by timtroendle** [comment]
This issue is scheduled for the v1.2 milestone. It may have been solved in 7b920d205361c3acbdb2f0e8db082d30cd1f5f4b but this commit is not merged to develop. I am therefore reopening this issue.

**Comment by timtroendle** [comment]
And I am closing it again in favour of #16 . #16 is a minimal model feature while this here is a technical task.
