### ISSUE TITLE
Split out datasets included in the project

### ISSUE THREAD

**Issue by suvayu** [calliope-project/euro-calliope#104]
Including datasets in the main repository means it is there for perpetuity making it progressively more difficult to work with the repository or distribute it in the future.  So ideally we want to split it out and pull it back in as a work flow step.  Possible implementations:
1. host externally at a data hosting service like zenodo
    - *Pro:* standard tools to download the data and include in any work flow
    - *Con:* signals that we are responsible for maintaining the dataset, and a rather permanent, which is counter to the goal "Euro Calliope should not include any raw data"
2. collect them in a separate "data repository" in GH under the Calliope organisation, add it as a submodule, and in the setup instructions include the step `git clone --recurse-submodules`
    - *Pro:* relatively simple and easy to manage versions
    - *Con:* working with git-submodules can be a little difficult for beginners, and probably not as flexible to be included any generic "add my dataset" rule to future work flows
3. same as (2) but do not use git-submodules, write a general rule to clone a dataset into the data directory
    - *Pro:* simple, easy to extend for other data sources
    - *Con:* managing versions is potentially manual (and tedious) process.

**Comment by sjpfenninger** [comment]
I'd be in favor of (3) for reasons of simplicity

**Comment by suvayu** [comment]
same here; simplicity and more extensibility in the future (including the option to remove it)

**Comment by timtroendle** [comment]
(3) seems to be the favourite option among people in the sprint.
