### ISSUE TITLE
Developer docs

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/euro-calliope#109]
Add more info on how to contribute

* development workflow
* testing
* git branch model

**Comment by timtroendle** [comment]
Importantly, this should include a release process. There are actually more and more elements to this:

* changelog
* version of euro-calliope
* version of eurocalliopelib
* version of euro-calliope-datasets
* ...

**Comment by timtroendle** [comment]
Also needed: how to build the documentation.

**Comment by timtroendle** [comment]
Also: remove the changelog to the top level and copy it into docs using a mkdocs plugin.
