### ISSUE TITLE
Some configuration value descriptions are broken

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#124]
In #111, all configuration values were added to the schema. In the same time, comments from the config file were removed and added as descriptions to the schema. For some comments, this makes sense, for others it does not. The latter ones must be fixed. Some of the comments should be reintroduced to the config in my opinion.

The reason why some descriptions are broken now is that some comments were not describing the configuration parameter, but the configuration parameter _value_.  For example, the comment `# from MW(h) to 100 GW(h)` told the reader that the configuration parameter value of `0.00001` was scaling from MW to 100 GW. When the value is changed, this comment is of course not valid anymore. Therefore, this description must be removed from the schema. In addition, I suggest to reintroduce the comment to the config.

**Comment by timtroendle** [comment]
Links to #47.

**Comment by brynpickering** [comment]
Ah, sorry about that. We did actively keep things in the default config that were related to the value (e.g. sources) but must not have been sufficiently thorough with it.
