### ISSUE TITLE
Add load_shedding option

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#131]
`load_shedding` is a technology that is included in the [default set of technologies](https://github.com/calliope-project/euro-calliope/blob/59e0951d89a4dbe60ad2c4aa39bf0e2967e25216/templates/renewable-techs.yaml#L89). This is error-prone and may be unnecessary.

It's error-prone because a user may not expect this technology to exist, leading to unintended results. Instead, it makes more sense to have this as an optional technology.

It may be unnecessary because it overlaps with [a built-in mechanism of Calliope](https://calliope.readthedocs.io/en/stable/user/building.html#allowing-for-unmet-demand).

Definition of done: It's either optional, or it's removed entirely.

**Comment by timtroendle** [comment]
@brynpickering , is it correct to say that this technology is useful because it provides the option to give unmet demand a cost -- something the built-in mechanism cannot do?

I understand the built-in mechanism can be controlled using the `BigM` value, but that is semantically different and changing it will have other, potentially unintended, consequences.

**Comment by brynpickering** [comment]
Indeed it does do the same as the built-in mechanism, but I prefer that it is explicit (and has the potential to actually embody costs of load shedding). Unmet demand as an inbuilt function is carrier agnostic and is really a debugging tool more than anything else. 

I would remove it entirely, as the only two uses of it don't fit with the core Euro-Calliope offering: 1. a research avenue to explore the system cost of load shedding when taking on specific technology deployment strategies, 2. a debugging tool when the model is infeasible. In the first instance, it is probably more relevant to have euro-calliope as a submodule of a study-specific analysis, where this technology would be easy to add. This opinion is far from a strong one. We could also just have it off by default. If your model is infeasible, you'll learn very quickly that it's switched off and not there to help you...

**Comment by timtroendle** [comment]
Thanks for these thoughts. I'd then make it available optionally. It's true that it's simple to implement to other projects, but having it as a standard option has some advantages.

**Comment by timtroendle** [comment]
This issue is invalid as load shedding is not part of the default model. Instead, load shedding is an override that is not properly documented and integrated. I'll hijack this issue to fix this.
