### ISSUE TITLE
Allow to run multiple years

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#152]
Euro-Calliope is built to run a single year. While it is possible to run multiple years, this requires manual work. Instead, there should be a built-in mechanism that automates this.

**Comment by brynpickering** [comment]
Ideally this would allow a user to define a start and end year in the config and all current single-year analyses would be iterated over to produce individual files. I could imagine the resulting model structure in `build` being:

```
model
-- non-resolution-specific YAMLs
-- [spatial_resolution]
---- spatial resolution-specific YAMLs
---- [year] 
-------- temporal and spatial resolution-specific YAMLs and CSVs
```

The alternative of having single CSVs with all years of data in one would require more work to concatenate CSVs which are currently specific to a single year (hydro and electricity demand, namely).
