### ISSUE TITLE
Add a FAQ // known issues section

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#159]
While this FAQ section can and should be extended and updated whenever appropriate, here's a list of FAQs to start with:

- [x] Snakemake appears frozen while running on the cluster. What can I do? (related to unresolved #93)
- [x] The workflow fails when trying to create a conda environment. How can I resolve this?
- [x] How do you link rules to files?
- [x] How to debug?
- [x] how long should I expect components of the workflow to take to run?
- [x] how do I propagate changes made in the configuration file to update the build?
- [x] Can you run the workflow for several different weather years?

**Comment by timtroendle** [comment]
@brynpickering , @FLomb , @wwwuFei , @FebinKa , @sjpfenninger , @suvayu , @jwohland: Is there anything else that would have helped you?

**Comment by suvayu** [comment]
All my confusions have been about:
- visibility of internal state, while debugging, or
- trying to run a subset of the rules.

Possibly useful FAQs could have been:
- the conditions under which (re)running a subset of the rules is possible;
- for debugging, I resorted to print statements, however it wasn't obvious where to put them, or if it was possible at all for certain situations (e.g. debugging "snakemake globs"), an entry addressing that would help.

**Comment by timtroendle** [comment]
Thanks @suvayu . I've added the debugging question. It came up before and it's certainly an important one.

For the rerunning question, let me ask so that I understand correctly. Do you mean "How to run parts of the workflow only, without executing the entire workflow?"

**Comment by brynpickering** [comment]
Who is this FAQ aimed at? I could imagine ones associated with development (e.g. working with different config files when working on features), but this looks more like it's aimed at running the workflow as-is... 

Another, based on internal conversations: 

* how long should I expect components of the workflow to take to run?

**Comment by suvayu** [comment]
yes, either because I am only rerunning part of the workflow because I changed something (say the year), or because I'm debugging a part of the workflow.

**Comment by brynpickering** [comment]
RE the changing of the year, I think we should address this with the question: "why are parts of the workflow not automatically re-running when I update the configuration file?" since it is really the only part of the whole process that isn't intuitive to the way snakemake is supposed to work... We should then either have a list of rules that are affected by each config option (possibly too hopeful) or recommend people rerun everything to be safe and wait on your corresponding snakemake PR to fix this...

**Comment by FLomb** [comment]
Perhaps this:
- Is there a sensible way to parallelise the workflow when, e.g., one needs to run it for several different weather years?
