### ISSUE TITLE
Add fully-electrified heat demand profiles

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#16]
Heat demand is one of the major demand sectors that needs including in Euro-Calliope, to research sectoral integration. The plan is to use the [When2Heat](https://github.com/oruhnau/when2heat) underlying code to produce heat demand profiles. The current code is hardcoded to produce nationally aggregated data, but could be updated to accept any arbitrary shape, since it only depends on weather and population data.

The reason for moving the functionality directly into Euro-Calliope, instead of adding When2Heat as a dependency is a. that we can choose to match the source of weather data with our source of PV capacity factors (currently MERRA2), including the grid spacing; b. slicing data to arbitrary shapes is already undertaken in Euro-Calliope, so the additional work *should* be low; and c. the temperature data could be further used to make heat pump COPs temperature dependent.

**Comment by sjpfenninger** [comment]
This needs porting across from Bryn's implementation in [balancing-act](https://github.com/timtroendle/balancing-act).

https://github.com/timtroendle/balancing-act/blob/main/scripts/construct/heat_profiles.py

This should also include the heat pump COP from [PR 24](https://github.com/timtroendle/balancing-act/pull/24).

**Comment by timtroendle** [comment]
To limit the scope of this issue, I suggest to build this as fully-electrified demand, even without heatpumps.

**Comment by brynpickering** [comment]
The balancing act contribution is just the cleanest one that has gone through internal review already.  It also runs much quicker than the old implementation, I believe. I assume by now you have basically fixed this part, although I haven't looked at the contribution @adrienmellot made.

**Comment by timtroendle** [comment]
Fixed within #408.
