### ISSUE TITLE
Add overview of administrative regions to the documentation

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#165]
This is to have some more images in the text. Being able to see all regions would be helpful.

Questions:
* How to handle the license of NUTS and GADM?
* Shall we show transmission links? If yes, which? Showing the all-neighbours-connected links may scare people off.

**Comment by brynpickering** [comment]
The NUTS license should be easy to handle by just mentioning the source in the figure, as per [their user agreement](https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units). [The GADM license](https://gadm.org/license.html) is a lot more vague and effectively allows us to publish maps produced from their data.

A map without the all-neighbours-connected links but with all 497 regions (+ bolder borders for countries) would be fine, although the all-connected plot looks quite appealing in the abstract (as used [here](https://www.callio.pe/model-gallery/)). With fewer regions (~100), It works quite well to show the links as well as the regions: https://github.com/calliope-project/euro-calliope-2.0.
