### ISSUE TITLE
Update to hydro power database release 07

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#19]
https://github.com/energy-modelling-toolkit/hydro-power-database/releases/tag/v7

**Comment by timtroendle** [comment]
See also #8 .

**Comment by timtroendle** [comment]
The dataset as introduced in #48 does not work: it contains unknown country codes. First, it contains entries for Kosovo. Second, it contains EU country code instead of ISO 3166 country code.

**Comment by brynpickering** [comment]
😔

**Comment by timtroendle** [comment]
I'm fixing it right now. Still, this is the third issue in less than 24h that could have been caught by CI. We should try to tackle #56 in same way.

**Comment by timtroendle** [comment]
There is another issue with 07: there are 4 duplicated indices in the dataset. See https://github.com/energy-modelling-toolkit/hydro-power-database/releases/tag/v8.
