### ISSUE TITLE
Reference all overrides in one file of scenarios

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#209]
### What can be improved?

Although all overrides are documented in the Euro-Calliope docs, it would make sense for ease of navigating the YAMLs to have a single file which points to all overrides. To do this, overrides could be turned into scenarios, e.g. `load-shedding: [load-shedding-override]`. In some cases, this is a chance to group overrides into scenarios.

Since Calliope v0.6.7, scenarios of scenarios are possible, so this would not remove the possibility of grouping overrides together, but would enable a user to quickly see what overrides are available without having to trawl through large YAMLs, where the overrides might be mixed with base tech/location definitions.

### Version

1.2.0.dev

**Comment by timtroendle** [comment]
I am not sure this is a good idea. See #236

**Comment by timtroendle** [comment]
The changelog says this is implemented. Close @brynpickering ?

**Comment by timtroendle** [comment]
This would break the modularity and is therefore not implemented. See as well #236 and #241.
