### ISSUE TITLE
Model metadata should be producible on chosen resolutions only

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#222]
### What happened?

Right now, model metadata can only be generated once models on all three resolutions are created.

This is an issue if one aims at creating a single model.

### Version

1.1.0

**Comment by brynpickering** [comment]
I suppose there is no real reason not to include the model metadata within the resolution-specific model files at this point. Even better would be to strip the config in the metadata of all info about the other resolutions...

**Comment by timtroendle** [comment]
We will implement this as part of the April sprint preparation.
