### ISSUE TITLE
Include mamba in base environment

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#227]
### What happened?

If a user doesn't have mamba installed then running snakemake fails by default since the user won't have overridden the conda prefix. This doesn't align with our wish that the workflow is as easy as possible to run out-of-the-box (so I deem it a "bug" ;) ). The easiest way I see to solving this is by including mamba in the euro-calliope environment file.

### Version

1.2.0.dev

**Comment by timtroendle** [comment]
Maybe I am making my life to easy, but I am leaning towards RTFM here. We have four not too difficult preparation steps and I think we can except people to read them. If they don't, and even if they have mamba installed, they may trip over missing Gurobi or missing CDS API.

I am absolutely for making their life as easy as possible and if we could automate this, I'd vote for it. But I don't see the possibility here.

We _could_ add this problem to the "troubleshooting" section. But if people aren't reading the short preparation section, I'm not optimistic they'd find the troubleshooting section.

**Comment by brynpickering** [comment]
> We could add this problem to the "troubleshooting" section. But if people aren't reading the short preparation section, I'm not optimistic they'd find the troubleshooting section.

Quite. OK, I'll close this in favour of RTFM.
