### ISSUE TITLE
Enable changes to spatial resolution layers and new layers

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#238]
### What can be improved?

Euro-Calliope depends on some upstream data processing (namely from https://github.com/calliope-project/solar-and-wind-potentials) downloaded from Zenodo which effectively fixes the resolution layers to those defined in the default Euro-Calliope workflow. This means that the config option `shapes` cannot be really be changed. In some instances it *can* be changed since the resulting unit ID will be the same as the downloaded data, but the underlying shapes might be subtly different  (see #237 for identified difference between NUTS and GADM shapes).

To enable a user to *either* change the existing spatial resolution layers or to add their own (e.g. with a mix of national and subnational units), the following datasets need to be made shape agnostic:

- [ ] Fraction of coast per unit (to distribute EEZs).
     Implement a more performant [shared_coast.py](https://github.com/calliope-project/solar-and-wind-potentials/blob/main/scripts/shared_coast.py) from our sister repository.

- [ ] Population (to distribute biofuels and to distribute demand - see next point)
    A high-res raster can be easily accessed from JRC open data portal (as is done in `solar-and-wind-potentials`).

- [ ] Demand per unit (to distribute electricity profiles to subnational units)
    Implement allocation of industry electricity demand using the EU-ETS and Eurostat datasets (where EU-ETS isn't available) (#63).
    Use a direct population raster to distribute non-industry demands.

- [ ] land eligibility (to set capacity limits for wind and solar)
    Upload a raster derived from https://github.com/calliope-project/solar-and-wind-potentials to Zenodo and do the final step of converting to availability per shape in this repository.

- [ ] land cover (to distribute biofuels)
    Same as with land eligibility.

If these steps are achieved, #76 can probably be closed, since a user can handle arbitrary shapes in a downstream workflow (either by injecting their own 'units.geojson' or by aggregating smaller administrative units). This approach would also align with #79.

### Version

1.2.0.dev

**Comment by timtroendle** [comment]
I don't really understand what this issue is about and how it differs from #76. Of course I agree that the current coupling between solar-and-wind-potentials isn't ideal. Let's discuss offline, @brynpickering.

I just want to throw in one more thought: Some of the issues can be solved by publishing the shapes _with_ the solar-and-wind-potentials. We didn't do this for licensing issues so far, but there may be possibilities that we could explore.

**Comment by brynpickering** [comment]
#76 is about handling any arbitrary shape, while this is about sticking with the syntax that shapes are linked to NUTS/GADM layer units, but enabling the user to select those. If a user for instance wants to use NUTS3 instead of GADM1 for most 'regional' units, or wants to do some at NUTS2 and others at NUTS3 etc. etc., then the current config supposedly enables that very easily. However, the `potentials` dependency means that it will break. 
The two issues are linked, though. I would close both simultaneously, since either would provide sufficient flexibility, but they are ultimately solving two slightly different issues.

> Some of the issues can be solved by publishing the shapes with the solar-and-wind-potentials

That only solves the issue that currently a user is given the impression that they *can* change the layer shapes, which would not be the aim.
