### ISSUE TITLE
Scipy warning: `Unknown solver options: xtol`

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#266]
### What happened?

When running the minimal workflow, a warning is raised on the line `res = minimize(residual, x0, method='nelder-mead', options={'xtol': 1e-10})` in `inflow_mwh.py` as the solver being used does not have that option available. Maybe it is meant to be `xatol` for the [nelder-mead method](https://docs.scipy.org/doc/scipy-1.6.2/reference/optimize.minimize-neldermead.html#optimize-minimize-neldermead)?

### Version

1.2.0.dev

**Comment by timtroendle** [comment]
Probably, yes. Weird that this warning appears only now, years after implementation. It may have to do with the fact that we did not pin the scipy version in `hydro.yaml` which likely we should do.
