### ISSUE TITLE
Mention and link pre-builts

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#28]

**Comment by timtroendle** [comment]
I wonder under which license the pre-builts can/must/should be published. The main data sources are:

* renewables.ninja for wind and solar capacity factors (CC-BY-NC)
* OPSD for load data (not sure about the licence here)
* Copernicus for hydro capacity factors ([Copernicus license](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=doc))

@brynpickering @sjpfenninger, do you have any experience with this?

**Comment by brynpickering** [comment]
No experience, but from I can see:
* OPSD is based on a bunch of probably differently licensed data, and they choose to say nothing about the licensing of the resulting aggregated data. 
* Copernicus license allows reproduction etc., they just require attribution it seems. 

That would leave renewables.ninja as the most restrictive license, and the one we should match?
