### ISSUE TITLE
Need to build model in ehighways resolution

### ISSUE THREAD

**Issue by jnnr** [calliope-project/euro-calliope#319]
- First, build spatial units for ehighways (see some comments in #318).
- Point to ehighways potentials: https://zenodo.org/records/6600619. This repo contains potentials for all resolutions, regional, national, continental, ehighways (It should also contain the polygons of the eligible areas)
- add another case to if-else-statement in https://github.com/calliope-project/euro-calliope/blob/6a58b335ad4ee378a895b8c7d8e793b4bf59c2be/scripts/transport/aggregate_timeseries.py#L71

**Comment by timtroendle** [comment]
This has been implement in #370.
