### ISSUE TITLE
ProtectedOutputException on data/automatic after making changes to code

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/euro-calliope#322]
### What happened?

When making changes to the workflow, if files in `data/automatic` are older than the rules that produce them, snakemake stops with a `ProtectedOutputException`. Attempting to get snakemake to accept the existing files without re-downloading them, I remove the write protection and `touch` the files. This still leads snakemake to then re-download them. So this seems no better than wiping `data/automatic`.  But there ought to be a better solution that leaves these files in place.

### Version

1.0.0

### Relevant log output

```shell
ProtectedOutputException in rule download_jrc_idees_zipped in file euro-calliope/./rules/data.smk, line 51:
Write-protected output files for rule download_jrc_idees_zipped:
    output: data/automatic/jrc-idees/HR.zip
    wildcards: country_code=HR
    affected files:
        data/automatic/jrc-idees/HR.zip
```

**Comment by brynpickering** [comment]
You should do `snakemake --cleanup-metadata <outfile>` to avoid it being run (doesn't require changing write permissions). Snakemake tells you this but it's easily lost in the info stream. Best way to catch the message is to first run with `--dry-run` as it is the only message that's shown.

**Comment by brynpickering** [comment]
Definition of done: update the documentation.

**Comment by brynpickering** [comment]
To add: `--cleanup-metadata data/automatic/**/*` will run it for the whole set of downloaded data files.
