### ISSUE TITLE
Add pre-commit to environment.yaml

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/euro-calliope#337]
### What happened?

EC has a pre-commit hook, but the regular environment.yaml does not include it.

To be safe, let's add it by default.

### Version

1.0.0

**Comment by timtroendle** [comment]
@irm-codebase if you agree with the discussion in #339 could you close this issue? If not, please let us know. :)

**Comment by irm-codebase** [comment]
Looks good to me!
