### ISSUE TITLE
Unecessary re-run triggers error for protected() files

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/euro-calliope#363]
### What happened?

# Issue

Snakemake usually triggers a rule re-run if the timestamps of [inputs and outputs differ](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#ignoring-timestamps).

In some cases, files downloaded into the `data/automatic` folder are re-downloaded because of this (usually `ch-energy-balance.xlsx`, `ch-industry-energy-balance.xlsx` and `eurostat-energy-balance.tsv.gz` in my case). This, in turn, causes the following error:

```shell
ProtectedOutputException in rule download_ch_energy_data in file /data/ivanruizmanuel/code/euro-calliope/./rules/data.smk, line 6:
Write-protected output files for rule download_ch_energy_data:
    output: data/automatic/ch-industry-energy-balance.xlsx
    wildcards: dataset=industry-energy-balance
    affected files:
        data/automatic/ch-industry-energy-balance.xlsx
```

This occurs because those rules use the `protected()` command for the output.

# Fix

I propose to swap `protected` for `ancient`, since it seems to reflect our needs better: initial downloads do not need to be re-run since they do not change.

See: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#ignoring-timestamps

# Reproduction

Run the following:

```
git checkout add-industry-module
snakemake -c 4 --use-conda "modules/industry/build/annual_demand_steel.csv"
```

Assuming you already had run the workflow for a different branch, you _should_ reach the `ProtectedOutputException` error...

### Version

1.0.0

### Relevant log output

```shell
$ snakemake -c 4 --use-conda "modules/industry/build/annual_demand_steel.csv"
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                               count    min threads    max threads
------------------------------  -------  -------------  -------------
annual_energy_balances                1              1              1
download_ch_energy_data               2              1              1
download_eurostat_energy_data         1              1              1
jrc_idees_industry_processed          2              4              4
jrc_idees_unzipped                    1              1              1
module_industry_steel_industry        1              1              1
total                                 8              1              4

Select jobs to execute...

[Thu Apr 18 10:34:37 2024]
Job 4: Get industry-energy-balance from Swiss statistics
Reason: Missing output files: data/automatic/ch-industry-energy-balance.xlsx; Code has changed since last execution

Activating conda environment: ../envs/snakemake/euro-calliope/24807c87b96b4ec7d81af28d1b8f0eab_
ProtectedOutputException in rule download_eurostat_energy_data in file /data/ivanruizmanuel/code/euro-calliope/./rules/data.smk, line 21:
Write-protected output files for rule download_eurostat_energy_data:
    output: data/automatic/eurostat-energy-balance.tsv.gz
    wildcards: dataset=energy-balance
    affected files:
        data/automatic/eurostat-energy-balance.tsv.gz
```

**Comment by irm-codebase** [comment]
> Isn't that solved via running `snakemake --cleanup-metadata data/automatic/**/*` ? I think this was added in the documentation FAQ recently by @brynpickering

Thanks, I was not aware of that! Still, it may be good to move to `ancient` if it fits our use-case. Is there any reason to stay with `protected`?

**Comment by timtroendle** [comment]
Reruns get triggered not only by timestamps, but also by: changes to the code, changes to the software environment, changes to the configuration of the rule.

I actually believe what you are seeing here has nothing to do with timestamps, because there are no inputs to these rules. I'd rather think they are based on changes to the envs because we've been changing them a lot recently. Usually, you wouldn't see so many reruns.

The protected downloads were intended exactly to avoid reruns when not explicitly intended.

If these reruns are indeed triggered by changes to the envs, I am not sure `ancient` is a solution as it seems entirely timestamp based. If they were a solution, they would be a slightly dangerous as required reruns could be missed. 

Honestly, I am not exactly sure what's the best solution but this seems like the safest -- even if admittedly most annoying -- solution.

**Comment by irm-codebase** [comment]
Took a bit to arrive to a test case that made sense...

I think you are right: it's mostly due to updates to the environments (specially for industry, since the PRs had a lot of merges due to other problems). So, not a real problem.

`ancient` could be added as additional protection for rules that use `protected` files as inputs, but only if this keeps being a hassle in the future.
