### ISSUE TITLE
Use conda envs for non-Python tools to increase portability

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#59]
All Python and close-to-Python tools run in a conda environment, which improves portability and reproducibility. Non-Python tools (like `curl` and `zip`) currently do not run within conda environments. As these tools are available on conda-forge, we should replace them with versions that are defined in a conda environment.

This _should_ allow to run the workflow on Windows (update README.md!), but I don't think we should officially support Windows.

**Comment by brynpickering** [comment]
I suspect it still wouldn't work on windows without updating all paths to being generated with `os.path.join`, to avoid the backslash/forward slash issue.

**Comment by timtroendle** [comment]
You are probably right. Still, we'd be one step closer to running on Windows and we'd be more portable in general. @febinKa may have run into this issue using the Windows Subsystem for Linux.
