### ISSUE TITLE
Optionally set transmission capacities based on ENTSOE TYNDP

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#61]
A possible dataset to depend on for transmission capacities is the ENTSOE TYNDP scenarios. The [2020 scenario data](https://2020.entsos-tyndp-scenarios.eu/wp-content/uploads/2020/06/TYNDP-2020-Scenario-Datafile.xlsx.zip) includes export and import capacities between countries / sub-national transmission markets for the scenario years 2025, 2030, and 2040. It should be possible to extract this data and optionally create international transmission capacity limits.

**Comment by timtroendle** [comment]
@brynpickering @FebinKa As we will need those anyways now, can we bring them right away into euro-calliope as an override?
