### ISSUE TITLE
Gap filling of load time series does not work for the default configuration

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#71]
In the current default configuration, load time series from 2016 is used for all countries in Europe. We have load data of Albania (ALB) only starting from 2017 and thus, `euro-calliope 1.0` used to use 2017 data for Albania.

The current gap filling method should do the same (as I understand it), but it does not do it. Therefore, `develop` is currently broken with the following error message: 

``AssertionError: Not enough load data for country ALB``

**Comment by timtroendle** [comment]
This is part of making load data pre-processing more flexible in #66.

**Comment by timtroendle** [comment]
Ping @brynpickering . Could you have a look at this? This is causing issues.

**Comment by brynpickering** [comment]
Odd, I'll look into it ASAP. Would you prefer this as a quick fix or to be fixed as part of my PR to resolve #66?

**Comment by timtroendle** [comment]
If possible, a hot fix would be great. @febinka stumbled upon this today.
