### ISSUE TITLE
Add electric vehicles with timeseries demand

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#81]
As part of adding transport demand (#17), we would resolve passenger and freight road transport. Both of these would be given in a demand for distance travelled over the year. Electric vehicles are an interesting component of our future energy system, and we should model the timeseries profile of their plug-in schedules. More vehicles plugged in = more potential to charge vehicles. The number of EVs the system chooses to invest in then dictates the quantity of battery capacity in the system and therefore the maximum potential for the system to charge vehicles (if 50% of vehicles are EVs and there are 100 million vehicles in total, and any EV has a 30kWh battery with 7kW max charge capability, then we can we can pump 350GW into EVs when they are all plugged in, or ~260GW when 75% are plugged in). 

In addition to this plug-in charge potential, we need to handle the fact that EV charge demand should be met at least on a weekly/monthly level. That is, the system *could* meet all demand based on charging all plugged-in vehicles at full capacity March-November, but this would give 3 months with no vehicles being charged. Conversely, it does not makes sense to use an hourly EV charge demand, since the reality is that electricity isn't needed at exactly the same time as it's being used. To model smart charging, we should allow the system to charge EVs whenever is most convenient on a system level, but such that all demand for electricity is still met at a weekly/monthly level.

Much of this functionality relies on updates to constraints and allowable timeseries parameters in Calliope (see constraints [here](https://github.com/calliope-project/calliope/blob/euro-calliope/calliope/backend/pyomo/constraints/eurocalliope.py)).

This has been implemented in our sector-coupled sibling [here](https://github.com/calliope-project/euro-calliope-2.0/blob/main/src/construct/hourly_ev_profiles.py) and in the form of new tech templates in this repositories [sector-coupled branch](https://github.com/calliope-project/euro-calliope/blob/sector-coupled/src/template/transport-techs.yaml).

- [ ] Add EV plug-in potential (RAMP-mobility)
- [ ] Add EV max charge capability based on number of vehicles (JRC IDEES)
- [ ] Add EV weekly/monthly demand (RAMP-mobility)

**Comment by timtroendle** [comment]
This duplicates or complements #271 .
