### ISSUE TITLE
Create new electricity load profile when sector coupling

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#83]
Some (relatively small) percentage of current electricity demand is used to meet demand for heat and transport. When adding in new sectors (e.g. transport #17 and heat #16) the relevant electricity demand should be removed from the electricity load profile. For sectors with timeseries (e.g. heat demand), this should be subtracted based on the profile shape. For sectors without, it might be best to remove as an even demand throughout the year.

In addition, new sources of electricity demand can be added directly to this profile. For instance, if considering all rail transport to be electrified, or some industry processes to be electrified (#63), the demands can be added to the electricity profile. The final profile will be an updated shape relative the the load profile from OPSD.

This has been implemented in our sector-coupled sibling [here](https://github.com/calliope-project/euro-calliope-2.0/blob/main/src/construct/electricity_with_other_sectors.py).

**Comment by timtroendle** [comment]
For road transport, this is implemented in #269. For other forms of heat and transport, this will be considered in the respective issues.
