### ISSUE TITLE
Electrify rail transport

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#84]
As part of adding in transport demand (#17), we should consider the ability to electrify all rail transport. This would take existing diesel consumption in rail and allocate the same rail distance to electricity (all using JRC IDEES). This can then be added to each region's electricity load profile (#83). 

This has been implemented in our sector-coupled sibling [here](https://github.com/calliope-project/euro-calliope-2.0/blob/main/src/construct/scale_hourly_transport_profiles.py). For lack of another source for rail demand profiles, I have used a profile from the DESTINEE model.

**Comment by timtroendle** [comment]
Closed in favour of #272.
