### ISSUE TITLE
Configurable sector inclusion

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#86]
By adding in all energy sectors, Euro-Calliope will be large. This can be computationally problematic and sometimes unnecessary to answer specific research questions. Accordingly 1. the choice of sectors to resolve in the model should be configurable and 2. whether or not to electrify a full sector should also be configurable.

Electrifying sectors could enable their inclusion in a power-system model by simply adding demand profiles to the electricity demand profile (as mentioned already in #83). This could then involve the implicit assumption that all heat and transport is electrified and that synthetic fuels are generated entirely by electricity.

This is not yet implemented in our sector-coupled sibling.

**Comment by timtroendle** [comment]
I am not sure what this issue comprises. Isn't this solved by #145?

**Comment by timtroendle** [comment]
^ @brynpickering

**Comment by timtroendle** [comment]
I am still under the impression that this is solved by #145. In #270 we now also have a first example of the full-electrification case. Hence, I am closing this issue.
