### ISSUE TITLE
Configurable carrier grouping

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#87]
As in #86, the fully resolved sector-coupled model may not be necessary for many research questions. Unlike #86, one might want to include a sector, but not at its full resolution. One example is whether or not to disaggregate 'space heat' and 'hot water', or to simply group it as 'heat'. Another example is whether or not to include hydrogen and CO2 demand streams in industry, or to electrify those demands and add them straight into the electricity demand profile but keep all other industry demand carriers. Finally, one could resolve several transport demand types (e.g. buses, motorcycles, commercial light-duty vehicles, etc.) or just represent them as 'light' and 'heavy' vehicles.

The two abovementioned examples are already implemented in our sector-coupled sibling (see configuration options [here](https://github.com/calliope-project/euro-calliope-2.0/blob/f6b85abc1245d0c9d35d437d39f2049c1710e63a/config/default.yaml#L82), [here](https://github.com/calliope-project/euro-calliope-2.0/blob/f6b85abc1245d0c9d35d437d39f2049c1710e63a/config/default.yaml#L73) and [here](https://github.com/calliope-project/euro-calliope-2.0/blob/f6b85abc1245d0c9d35d437d39f2049c1710e63a/config/default.yaml#L62)) but the effort isn't consistent and they are prone to errors. For example, I currently rely on the model working with space heating and water heating grouped as 'heat', and I don't think the [heat tech YAML templates](https://github.com/calliope-project/euro-calliope/blob/sector-coupled/src/template/heat-techs.yaml) will actually work with going back to space heating and water heating as independent streams.

**Comment by timtroendle** [comment]
This is not exactly a feature, but a modeling philosophy. The foundation is layed within #145, now we just need to adhere. If there is a specific split that is required, I suggest to open separate, concrete issues.
